In [8]:
# for X in ITERABLE: STATEMENT
import numpy as np

In [3]:
x_list = [1,2,3]
x_tuple = (1,2,3)
x_set = {1,2,3}
x_dict = {'a':1,'b':2,'c':3}
x_array = np.array([1,2,3])
x_range = range(1,4,1)

for num in x_list:
    print(num)

1
2
3


In [4]:
for num in x_tuple:
    print(num)

1
2
3


In [5]:
for num in x_set:
    print(num)

1
2
3


In [6]:
for num in x_dict:
    print(num)

a
b
c


In [7]:
for num in x_array:
    print(num)

1
2
3


In [8]:
for num in x_range:
    print(num)

1
2
3


In [9]:
# 컨테이너를 만들고 값을 하나하나 받아오는걸iterable

In [10]:
i = 1
print(i)
i = 2
print(i)
i = 3 
print(i)

1
2
3


In [10]:
import time
for  i  in [1,2,3,4,5]:
    print('i='+str(i))
    time.sleep(1)

i=1
i=2
i=3
i=4
i=5


In [14]:
i

5

In [ ]:
for  i  in range(1,101,1):
    print('i='+str(i))
    time.sleep(0.1)

In [18]:
for  i  in np.linspace(1,100,100):
    print('i='+str(i),end='\t')
    time.sleep(0.01)

i=1.0	i=2.0	i=3.0	i=4.0	i=5.0	i=6.0	i=7.0	i=8.0	i=9.0	i=10.0	i=11.0	i=12.0	i=13.0	i=14.0	i=15.0	i=16.0	i=17.0	i=18.0	i=19.0	i=20.0	i=21.0	i=22.0	i=23.0	i=24.0	i=25.0	i=26.0	i=27.0	i=28.0	i=29.0	i=30.0	i=31.0	i=32.0	i=33.0	i=34.0	i=35.0	i=36.0	i=37.0	i=38.0	i=39.0	i=40.0	i=41.0	i=42.0	i=43.0	i=44.0	i=45.0	i=46.0	i=47.0	i=48.0	i=49.0	i=50.0	i=51.0	i=52.0	i=53.0	i=54.0	i=55.0	i=56.0	i=57.0	i=58.0	i=59.0	i=60.0	i=61.0	i=62.0	i=63.0	i=64.0	i=65.0	i=66.0	i=67.0	i=68.0	i=69.0	i=70.0	i=71.0	i=72.0	i=73.0	i=74.0	i=75.0	i=76.0	i=77.0	i=78.0	i=79.0	i=80.0	i=81.0	i=82.0	i=83.0	i=84.0	i=85.0	i=86.0	i=87.0	i=88.0	i=89.0	i=90.0	i=91.0	i=92.0	i=93.0	i=94.0	i=95.0	i=96.0	i=97.0	i=98.0	i=99.0	i=100.0	

In [20]:
for  i  in (1,2,3,4,5):
    print('i='+str(i),end='\t')
    time.sleep(1)

i=1	i=2	i=3	i=4	i=5	

In [21]:
# string
for i in '12345':
    print('i='+i)
    time.sleep(1)

i=1
i=2
i=3
i=4
i=5


In [22]:
for i in 'abcde':
    print('i='+i)
    time.sleep(1)

i=a
i=b
i=c
i=d
i=e


In [23]:
for i in 'Python':
    print('i='+i)
    time.sleep(1)

i=P
i=y
i=t
i=h
i=o
i=n


In [25]:
for i in {1,2,3,4,5}:
    print('i='+str(i),end='\t')
    time.sleep(1)

i=1	i=2	i=3	i=4	i=5	

In [33]:
# dictionary
D = {'P1':20,'P2':22,'P3':25}
for i  in D.values(): #.keys .value . items
    print('i='+str(i),end="\t")
    time.sleep(1)

i=20	i=22	i=25	

In [27]:
D.items()

dict_items([('P1', 20), ('P2', 22), ('P3', 25)])

In [28]:
D.keys()

dict_keys(['P1', 'P2', 'P3'])

In [29]:
D.values()

dict_values([20, 22, 25])

In [34]:
# array
for i in  np.array([1,2,3]):
    print('i='+str(i),end="\t")
    time.sleep(1)

i=1	i=2	i=3	

In [36]:
# multiple loop
for i in [1,2,3]:
    for j in [1,2,3]:
        print('i=',str(i),end='\t')
        print('j=',str(j),end='\t')
        print('')
        time.sleep(1)

i= 1	j= 1	
i= 1	j= 2	
i= 1	j= 3	
i= 2	j= 1	
i= 2	j= 2	
i= 2	j= 3	
i= 3	j= 1	
i= 3	j= 2	
i= 3	j= 3	


In [44]:
for i in range(2,10,1):
    for j in range(1,10,1):
        print('{}단 = {}*{}={}'.format(i,i,j,i*j),end=' ')

        time.sleep(0.1)

2단 = 2*1=2 2단 = 2*2=4 2단 = 2*3=6 2단 = 2*4=8 2단 = 2*5=10 2단 = 2*6=12 2단 = 2*7=14 2단 = 2*8=16 2단 = 2*9=18 3단 = 3*1=3 3단 = 3*2=6 3단 = 3*3=9 3단 = 3*4=12 3단 = 3*5=15 3단 = 3*6=18 3단 = 3*7=21 3단 = 3*8=24 3단 = 3*9=27 4단 = 4*1=4 4단 = 4*2=8 4단 = 4*3=12 4단 = 4*4=16 4단 = 4*5=20 4단 = 4*6=24 4단 = 4*7=28 4단 = 4*8=32 4단 = 4*9=36 5단 = 5*1=5 5단 = 5*2=10 5단 = 5*3=15 5단 = 5*4=20 5단 = 5*5=25 5단 = 5*6=30 5단 = 5*7=35 5단 = 5*8=40 5단 = 5*9=45 6단 = 6*1=6 6단 = 6*2=12 6단 = 6*3=18 6단 = 6*4=24 6단 = 6*5=30 6단 = 6*6=36 6단 = 6*7=42 6단 = 6*8=48 6단 = 6*9=54 7단 = 7*1=7 7단 = 7*2=14 7단 = 7*3=21 7단 = 7*4=28 7단 = 7*5=35 7단 = 7*6=42 7단 = 7*7=49 7단 = 7*8=56 7단 = 7*9=63 8단 = 8*1=8 8단 = 8*2=16 8단 = 8*3=24 8단 = 8*4=32 8단 = 8*5=40 8단 = 8*6=48 8단 = 8*7=56 8단 = 8*8=64 8단 = 8*9=72 9단 = 9*1=9 9단 = 9*2=18 9단 = 9*3=27 9단 = 9*4=36 9단 = 9*5=45 9단 = 9*6=54 9단 = 9*7=63 9단 = 9*8=72 9단 = 9*9=81 

In [19]:
# iterate()
x_list = [1,2,3]

x_iter = iter(x_list)


In [22]:
next(x_iter)

3

In [1]:
x_str = 'abc'
x_iter = iter(x_str)

In [4]:
next(x_iter)

'c'

In [6]:
# indentation
for i in range(3):
    print('Inside For loop')
print('Outside for loop') #인덴트 이해했지?

Inside For loop
Inside For loop
Inside For loop
Outside for loop


In [14]:
# enumerate
M = np.array([10,20,30])
VIP = ['Nweton','Kepler',"Euler"]
PD = {'P1':25,'P2':28,'P3':24}

for cnt, value in enumerate(PD.values(),start=1):
    print(cnt)
    print(value)
    print('')
    time.sleep(1)

1
25

2
28

3
24



In [18]:
# zip
for i in zip(M,VIP,PD.items()):
    print(i)
    time.sleep(1)

(10, 'Nweton', ('P1', 25))
(20, 'Kepler', ('P2', 28))
(30, 'Euler', ('P3', 24))


In [23]:
#example 1 - for loop
s = 'Best Company. Tel: 777-7777'
for i in range(5):
    print(s)
    print('')

Best Company. Tel: 777-7777

Best Company. Tel: 777-7777

Best Company. Tel: 777-7777

Best Company. Tel: 777-7777

Best Company. Tel: 777-7777



In [24]:
# example 2 - for loop
VIP = ['Kepler','Newton','Euler']
for i in VIP:
    print('Name : ' + i)
    print('Great Paty 2022')
    print('')

Name : Kepler
Great Paty 2022

Name : Newton
Great Paty 2022

Name : Euler
Great Paty 2022



In [25]:
# example 3 - for loop
x = np.array([10,20,30,40,50])
for i in x:
    print(i**2)
    time.sleep(1)

100
400
900
1600
2500


In [28]:
y = np.zeros(x.shape)
for idx, value in enumerate(x):
    y[idx] = value**2
    print(y)
    time.sleep(1)

[100.   0.   0.   0.   0.]
[100. 400.   0.   0.   0.]
[100. 400. 900.   0.   0.]
[ 100.  400.  900. 1600.    0.]
[ 100.  400.  900. 1600. 2500.]


In [30]:
x = np.array([10.,20.,30.])
y = x**2
y

array([100., 400., 900.])