In [1]:
import numpy
a = numpy.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
a = numpy.array([10,20,30])
a

array([10, 20, 30])

In [3]:
import numpy as np
a = np.array([10,20,30])
a


array([10, 20, 30])

In [4]:
#size related variables
a

array([10, 20, 30])

In [5]:
a.shape #어레이의 사이즈(1차원이니까 3개라고 3,라고 표현)
a.ndim # 디멘션이 몇개냐고 물어보는거 차원 이 1차원이니까 1
a.dtype # 어레이의 데이터 타입을 알려주는것
a.itemsize #어레이 데이터 타입이 몇바이트를 쓰는지 알려주는것
a.size # 어레이의 값이 몇개가 들어갔는지 알려주는것
type(a) #numpy.ndarray 라고 나오는데 nd 는 N-dimensional array
        #N 이라는것은 차원을 아무것이나 넣을수 있다는것

numpy.ndarray

In [6]:
a= np.array([10,20,30])
a.dtype

a[2] = 30.1

a.dtype
a

array([10, 20, 30])

In [7]:
a.dtype.name
a = a.astype('float64')
a[2] = 30.1
a
a.dtype.name

'float64'

In [8]:
b= np.array([10.,20.,30.])
b
b.dtype.name

'float64'

In [9]:
c= np.array([10.1,20.1,30.1],'int32')
c
c.dtype.name

'int32'

In [10]:
# divide by 2
x = np.array([7,9,11])
y = x/2
y
y.dtype
x.dtype

dtype('int32')

In [11]:
#int32 vs int 64
#2147483647
x = np.array([0])
x[0] = 2147483647
x

array([2147483647])

In [12]:
x[0] = x[0]+1 #32비트 최대값을 넘어갔기에 overflow 오류가 난다

C:\Users\goror\AppData\Local\Temp\ipykernel_2244\3974120513.py:1: RuntimeWarning: overflow encountered in long_scalars
  x[0] = x[0]+1


In [13]:
x = np.array([0],'int64')
x[0] = 2147483647
x

array([2147483647], dtype=int64)

In [14]:
x[0] = x[0]+1 #64비트로 바꾸엇기에 오류가 나지 않는다
x

array([2147483648], dtype=int64)

In [15]:
x[0] = 9223372036854775807 #64비트의 한계수
x

array([9223372036854775807], dtype=int64)

In [16]:
x[0] = x[0]+1 #64비트 정수형 한계를 넘었다
x

C:\Users\goror\AppData\Local\Temp\ipykernel_2244\429370096.py:1: RuntimeWarning: overflow encountered in longlong_scalars
  x[0] = x[0]+1 #정수형 한계를 넘었다


array([-9223372036854775808], dtype=int64)

In [18]:
x = np.array([10.,20.])
x
x.dtype
# max value 1.7976931348623158*E+308 E의 308승까지 표현 가능하고 이걸 넘어가면 infinity
# using float64

dtype('float64')

In [20]:
a = np.array([10,20,30])

In [21]:
a = np.array([10,'abc',30])

In [22]:
a.dtype

dtype('<U11')

In [23]:
2*a

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('int32'), dtype('<U11')) -> None

In [24]:
a = np.array([10.,20.,30.])

In [25]:
#make 2D array
a = np.array([ [10,20,30],[40,50,60] ])

In [26]:
a.shape #2차원에 값이 3개씩 있다는 뜻

(2, 3)

In [29]:
print(a.itemsize) #4바이트씩 할당
a.dtype

4


dtype('int32')

In [30]:
a.size #총갯수가?

6

In [31]:
a = np.array([ [10,20,30],[40,50,60],[70,80,90] ])

In [33]:
a.shape
#numpy 홈페이지 index 예제를 살펴보면서 이해해야 된다.

(3, 3)

In [35]:
a= np.array(
    [
        [[10,50],[20,60]],
        [[30,70],[40,80]]
    ]
)

In [36]:
a.ndim #몇차원이지 ?

3

In [4]:
# complex numbers 복소수
import numpy as np
a = np.array([10+10j, 20+20j])
a

array([10.+10.j, 20.+20.j])

In [9]:
a= np.array([10,20],'complex')
print(a.dtype)
print(a)

complex128
[10.+0.j 20.+0.j]


In [13]:
# matrix
a= np.array([10,20])
b= np.matrix([10,20]) #2차원만 만듬

In [11]:
a

array([10, 20])

In [14]:
b

matrix([[10, 20]])

In [15]:
b = np.matrix([[10,20],[30,40]])

In [16]:
b

matrix([[10, 20],
        [30, 40]])

In [17]:
b = np.matrix([[[10]]]) #3차원은 만들수없다

ValueError: matrix must be 2-dimensional

In [18]:
# insert
a = np.array([10,20,30])
a = np.insert(a,0,5)

In [19]:
a

array([ 5, 10, 20, 30])

In [22]:
# delete
np.delete(a,0)

array([10, 20, 30])

In [23]:
# Array Generation Funtions
a = np.array([1,2,3])



array([ 5, 10, 20, 30])

In [25]:
a = np.arange(3)
a

array([0, 1, 2])

In [26]:
a = np.zeros((2,3)) #빈값으로 차원 배열 공간을 만듬
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
a = np.ones((2,3)) #빈값 대신 1으로 채워줌
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
a = np.linspace(0,5,6) #0부터 5 까지 6개로 나눠서 배열 만들기
a

array([0., 1., 2., 3., 4., 5.])

In [29]:
a = np.logspace(0,5,11) #10의 0승 부터  10의 5승 까지 11개로 숫자를 나눠서 로그 배열 을 만들어줌
a

array([1.00000000e+00, 3.16227766e+00, 1.00000000e+01, 3.16227766e+01,
       1.00000000e+02, 3.16227766e+02, 1.00000000e+03, 3.16227766e+03,
       1.00000000e+04, 3.16227766e+04, 1.00000000e+05])

In [30]:
# Basic Opertations

a = np.array([10, 20, 30])
b = np.array([ 1,  2,  3])

In [32]:
c = a + b
c

array([11, 22, 33])

In [33]:
c = a - b
c

array([ 9, 18, 27])

In [34]:
c = b**2
c

array([1, 4, 9], dtype=int32)

In [35]:
c = 2*a
c

array([20, 40, 60])

In [36]:
idx = b < 20
idx

array([ True,  True,  True])

In [40]:
idx = a <20
idx

array([ True, False, False])

In [38]:
type(idx)

numpy.ndarray

In [41]:
a = a + 1
a

In [44]:
a += 1
a

array([13, 23, 33])

In [46]:
a *= 2
a

array([ 52,  92, 132])

In [47]:
a = np.array([10,20,30]) #타입이 다르니까 맞춰줘야 계산이 된다
b = np.array([1.,2.,3.])

In [48]:
a+=b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [68]:
a = np.array([10.,20.,30.])
b = np.array([1.,2.,3.])


In [69]:
a+=b

In [61]:
a.dtype

dtype('float64')

In [70]:
a = np.array([10,20,30])
b = np.array([1,2,3])

In [71]:
np.add(a,b) #더하기

array([11, 22, 33])

In [72]:
np.subtract(a,b) #빼기

array([ 9, 18, 27])

In [73]:
np.multiply(a,b) #곱하기

array([10, 40, 90])

In [74]:
np.divide(a,b) #나누기

array([10., 10., 10.])

In [75]:
np.divmod(a,b) #나누셈 하고 나머지

(array([10, 10, 10], dtype=int32), array([0, 0, 0], dtype=int32))

In [76]:
np.exp(b) #e에 1 승 2 승 3승

array([ 2.71828183,  7.3890561 , 20.08553692])

In [78]:
np.sqrt(b) #제곱근을 적용해서 계산

array([1.        , 1.41421356, 1.73205081])

In [93]:
a = np.array([10,20,30])

In [80]:
np.mean(a) #값의 평균

20.0

In [81]:
a.mean()

20.0

In [82]:
np.average(a)

20.0

In [83]:
np.average(a,weights=[1,1,1]) #평균을 구하는데 가중치를 정할수 있다

20.0

In [84]:
np.average(a, weights=[1,1,0])

15.0

In [85]:
np.average(a,weights=[0,1,1])

25.0

In [86]:
np.average(a,weights=[1,0,1])

20.0

In [87]:
np.median(a)

20.0

In [89]:
np.cumsum(a) #피보나치 수열?

array([10, 30, 60], dtype=int32)

In [94]:
np.cov(a)  

array(100.)

In [96]:
np.std(a)

8.16496580927726

In [97]:
np.var(a)

66.66666666666667