In [2]:
import numpy as np
x = np.array([10,20,30])

In [3]:
y = x.sum()
y

60

In [4]:
x = np.array([10.,20.,30.,25.,15.])

In [5]:
x.min()

10.0

In [6]:
x.argmin()

0

In [7]:
x_min, x_min_idx = x.min(), x.argmin()

In [8]:
x_min

10.0

In [9]:
x_min_idx

0

In [10]:
x.max()

30.0

In [11]:
x_max , x_max_idx = x.max() , x.argmax()

In [12]:
x_max

30.0

In [13]:
x_max_idx

2

In [14]:
x.sort()

In [15]:
x

array([10., 15., 20., 25., 30.])

In [16]:
x = np.array([10.,20.,30.,25.,15.])
y = np.sort(x)

In [17]:
x

array([10., 20., 30., 25., 15.])

In [18]:
y

array([10., 15., 20., 25., 30.])

In [19]:
idx = np.argsort(x) #sort되기전에 원래 index를 찾아주는 함수

In [20]:
idx

array([0, 4, 1, 3, 2], dtype=int64)

In [21]:
y = x [idx]

In [22]:
y

array([10., 15., 20., 25., 30.])

In [23]:
a=np.array([10,20,30])
b=np.array([-5,25])
np.searchsorted(a,b) #어디에 위치해야 sort되는지 찾아주는 함수

array([0, 2], dtype=int64)

In [26]:
d = np.arange(1,7,1)
d

array([1, 2, 3, 4, 5, 6])

In [25]:
d.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
e = d.reshape(2,3)
e

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
f=np.linspace(1,10,10)
f

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [29]:
g = np.linspace(1,10,10).reshape(2,5)
g

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [32]:
a =np.array([[1,2],[3,4]])


In [33]:
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [34]:
np.repeat(a,2,axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [35]:
np.repeat(a,2,axis=1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [36]:
np.repeat(a,2,axis=2) #디멘션이 2차원이기에 3차원은 존재하지 않아서 에러

AxisError: axis 2 is out of bounds for array of dimension 2

In [37]:
np.repeat(a,[1,2],axis=0) #앞에건 한번 뒤에는 두번반복

array([[1, 2],
       [3, 4],
       [3, 4]])

In [38]:
np.repeat(a,[3,1],axis=0) #0번인덱스는 3번 반복  1번인덱스는 1번

array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4]])

In [39]:
np.repeat(a,[1,2],axis=1)

array([[1, 2, 2],
       [3, 4, 4]])

In [40]:
np.repeat(a,[3,1],axis=1)

array([[1, 1, 1, 2],
       [3, 3, 3, 4]])

In [43]:
a=np.array([[1],[2],[3]])
b=np.array([[4],[5],[6]])


In [44]:
np.concatenate((a,b),axis=0)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [45]:
np.concatenate((a,b),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [46]:
np.concatenate((a,b),axis=2) #3차원은 없기때문에 에러

AxisError: axis 2 is out of bounds for array of dimension 2

In [47]:
a= np.array([10,20,30])
b= np.array([40,50,60])


In [48]:
np.vstack((a,b))

array([[10, 20, 30],
       [40, 50, 60]])

In [49]:
np.hstack((a,b))

array([10, 20, 30, 40, 50, 60])

In [50]:
A = np.array([[10.,20.,30.],
              [40.,50.,60.]])

In [53]:
# np.hsplit(A,2) #값이 2개가 아니기에 에러
np.hsplit(A,3)

[array([[10.],
        [40.]]),
 array([[20.],
        [50.]]),
 array([[30.],
        [60.]])]

In [54]:
B = np.vsplit(A,2)

In [55]:
B[0]

array([[10., 20., 30.]])

In [56]:
B[1]

array([[40., 50., 60.]])

In [57]:
type(B) #브이스필릿은 다따로 때내어 리스트에 저장

list

In [59]:
type(B[0]) #하지만 리스트안에 값타잎은 어레이 타입이다

numpy.ndarray

In [60]:
A = np.array([[10,20,30],[40,50,60]])

In [61]:
A.transpose()

array([[10, 40],
       [20, 50],
       [30, 60]])

In [62]:
A.ravel() #2차원을 1차원으로

array([10, 20, 30, 40, 50, 60])

In [64]:
A.ravel(order='C') #C=style: row-major

array([10, 20, 30, 40, 50, 60])

In [65]:
A.ravel(order='F') #Fortran-style: colum-major

array([10, 40, 20, 50, 30, 60])

In [66]:
A.flatten()

array([10, 20, 30, 40, 50, 60])

In [67]:
A=np.array([[1,2,3]])

In [68]:
A.squeeze() #차원이 필요없을때 없앨수 있다

array([1, 2, 3])

In [4]:
A = np.array([ [[1,2]],
               [[3,4]],
               [[4,5]] ])

In [70]:
A

array([[[1, 2]],

       [[3, 4]],

       [[4, 5]]])

In [8]:
B = A.squeeze()

In [9]:
B

array([[1, 2],
       [3, 4],
       [4, 5]])

In [5]:
A.shape

(3, 1, 2)

In [10]:
B.shape

(3, 2)

In [11]:
#[1,2,3] and [4,5,6]
#
#[1,4]
#[2,5]
#[3,6]
A1 = np.array([1,2,3])
B1 = np.array([4,5,6])

In [13]:
A2 = A1[:,np.newaxis]
B2 = B1[:,np.newaxis]
print(A2)
print(B2)

[[1]
 [2]
 [3]]
[[4]
 [5]
 [6]]


In [14]:
A2.shape

(3, 1)

In [15]:
B2.shape

(3, 1)

In [16]:
np.concatenate((A2,B2),axis=0)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [17]:
np.concatenate((A2,B2),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [29]:
# idea 2
C=np.vstack((A1,B1)).transpose()
C

array([[1, 4],
       [2, 5],
       [3, 6]])

In [27]:
# idea 3 
np.hstack((A1,B1)).reshape(2,3).transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [30]:
A = np.array([10,20,30])
B = A
B[0]=99

In [31]:
B

array([99, 20, 30])

In [32]:
B is A

True

In [34]:
print(id(A))
id(B)

2100707952752


2100707952752

In [35]:
# shallow copy
A=np.array([10,20,30,40])
B=A.view()

In [36]:
B is A

False

In [37]:
print(id(A))
id(B)

2100707954384


2100707910928

In [38]:
B.shape = (2,2)

In [39]:
B

array([[10, 20],
       [30, 40]])

In [40]:
B[0][1]

20

In [41]:
B[0][1] =7
B

array([[10,  7],
       [30, 40]])

In [42]:
A

array([10,  7, 30, 40])

In [43]:
# 쉘로우 카피는 메모리상의 데이터는 같이 공유는 하고있지만 어레이 자체의 쉐입은 틀려도 상관이없다

In [44]:
# deep copy
A= np.array([10,20,30,40])
B= A.copy()

In [45]:
B[0]

10

In [46]:
B[0]=99

In [47]:
B

array([99, 20, 30, 40])

In [49]:
B is A

False

In [50]:
B.base is A

False

In [51]:
B.flags.owndata

True

In [52]:
print(id(A))
id(B)

2100673543696


2100707909968

In [53]:
%reset -f