In [1]:
# logic functions
import numpy as np

In [4]:
a = np.array([0,1,2])

In [3]:
a.all() #모두 참이냐 물어보는것

False

In [5]:
a.any() #하나라도 참이 있나 물어보는함수

True

In [8]:
b = a.nonzero() #a 어레이에 제로가 아닌값을 찾는것
b

(array([1, 2], dtype=int64),)

(array([1, 2], dtype=int64),)

In [10]:
a = np.array([0,10,20])

In [12]:
np.where(a>0)

(array([1, 2], dtype=int64),)

In [13]:
a = np.array([10,0,20])
np.where(a>0)

(array([0, 2], dtype=int64),)

In [14]:
np.where(a==0)

(array([1], dtype=int64),)

In [15]:
np.where(a<0)

(array([], dtype=int64),)

In [16]:
# indexing & slicing

M1 = np.array([ 100.,
                101.,
                102.,
                103.,
                104.])

In [17]:
M1.shape

(5,)

In [18]:
M1.ndim

1

In [19]:
M1[0]

100.0

In [20]:
M1[1]

101.0

In [21]:
M1[-1]

104.0

In [22]:
M1[-5]

100.0

In [23]:
M1[[0,2]]

array([100., 102.])

In [24]:
M1[[2,4]]

array([102., 104.])

In [25]:
M1[0:3]

array([100., 101., 102.])

In [26]:
M1[0:3:1]

array([100., 101., 102.])

In [27]:
M1[0:3:2]

array([100., 102.])

In [28]:
M1[:]

array([100., 101., 102., 103., 104.])

In [31]:
M1[::-1]

array([104., 103., 102., 101., 100.])

In [33]:
M2 = np.array(  [
                [100.,101.,102],
                [200.,201.,202]
                ])

In [34]:
M2.shape

(2, 3)

In [35]:
M2.ndim

2

In [38]:
M2[0][0]
M2[0,0]

100.0

In [39]:
M2[0][2]
M2[0,2]

102.0

In [41]:
M2[1][1]
M2[1,1]

201.0

In [43]:
M2[1][2]
M2[1,2]

202.0

In [44]:
M2[:,:]

array([[100., 101., 102.],
       [200., 201., 202.]])

In [45]:
M2[0,:]

array([100., 101., 102.])

In [46]:
M2[1,:]

array([200., 201., 202.])

In [48]:
M3 = np.array(
    [
        [
            [100.,101.,102.,103.],
            [104.,105.,106.,107.],
            [108.,109.,110.,111.]        
        ],
        [
            [200.,201.,202.,203.],
            [204.,205.,206.,207.],
            [208.,209.,210.,211.]        
        ]
    ]
)

In [49]:
M3.shape

(2, 3, 4)

In [50]:
M3.ndim

3

In [51]:
M3[0,0,0]

100.0

In [52]:
M3[0,:,:]

array([[100., 101., 102., 103.],
       [104., 105., 106., 107.],
       [108., 109., 110., 111.]])

In [53]:
M3[1,:,:]

array([[200., 201., 202., 203.],
       [204., 205., 206., 207.],
       [208., 209., 210., 211.]])

In [54]:
x=np.array([10.,20.,30.])

In [55]:
idx = np.where(x==30)
x[idx]

array([30.])

In [56]:
idx = np.where(x==30.)

In [57]:
idx=(x==30)
x[idx]

array([30.])

In [58]:
idx

array([False, False,  True])

In [59]:
# where() or nonzero()
x[np.where(x==30)]

array([30.])

In [60]:
np.nonzero(x==30)

(array([2], dtype=int64),)

In [61]:
# image
IMAGE = np.array([[255,0,255],[255,0,255],[255,0,255]])
idx = np.where(IMAGE==255)
IMAGE[idx] = 0

In [62]:
IMAGE

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [63]:
# linear algebra

M = np.array([[10,20],[30,40]])
N = np.array([[1,2],[3,4]])

In [64]:
M * N

array([[ 10,  40],
       [ 90, 160]])

In [66]:
M @ N

array([[ 70, 100],
       [150, 220]])

In [67]:
M.dot(N)

array([[ 70, 100],
       [150, 220]])

In [73]:
a = np.zeros((3,3))
b = np.ones((3,3))

c = np.trace(b) #대각선으로 더한 값을 b에 저장함 3이되겠지

In [76]:
M = np.array([[1.,-3.],[2.,4.]])
y = np.array([[1.],[3.]])

In [75]:
M_inv = np.linalg.inv(M)

In [78]:
x = M_inv@y #해를 구하기
x

array([[1.3],
       [0.1]])

In [80]:
x=np.linalg.solve(M,y) #위에 찾는 걸 한줄로 넘파이가 제공하는 함수 linear algebra
x

array([[1.3],
       [0.1]])

In [81]:
np.linalg.eig(M) #고유 백터 고유 값

(array([2.5+1.93649167j, 2.5-1.93649167j]),
 array([[ 0.77459667+0.j ,  0.77459667-0.j ],
        [-0.38729833-0.5j, -0.38729833+0.5j]]))

In [85]:
# singular value decomposition
np.linalg.svd(M)

N=np.zeros((5,5))
N

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [84]:
np.fill_diagonal(N,100)
N

array([[100.,   0.,   0.,   0.,   0.],
       [  0., 100.,   0.,   0.,   0.],
       [  0.,   0., 100.,   0.,   0.],
       [  0.,   0.,   0., 100.,   0.],
       [  0.,   0.,   0.,   0., 100.]])

In [86]:
#More Examples
# 2차원 배열에 첫 줄 은 1로 곱 두 줄은 2로 곱 3줄은 3으로 곱 하고싶을때

In [92]:
A = np.array([[10,20,30],[40,50,60],[70,80,90]])


In [93]:
B = np.array([[1],[2],[3]])

In [88]:
B = B.repeat(3,axis=1)
B

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [91]:
C=A*B
C

array([[ 10,  20,  30],
       [ 80, 100, 120],
       [210, 240, 270]])

In [96]:
A.shape

(3, 3)

In [97]:
B.shape

(3, 1)

In [94]:
# broadcasting
# 원소대 원소를 곱하려면 원래 행렬이 틀리기때문에 되지않지만 파이썬기능으로 넘파이 에서 알아서 맞춰서 해주는것 
D = A*B
D

array([[ 10,  20,  30],
       [ 80, 100, 120],
       [210, 240, 270]])

In [98]:
# function usage exmple
def f(x,y):
    return x*y
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  0,  0,  0],
       [ 0,  1,  2,  3],
       [ 0,  2,  4,  6],
       [ 0,  3,  6,  9],
       [ 0,  4,  8, 12]])

In [99]:
# set
a= np.array([10,20,30,40,50])
b= np.array([30,50])
np.setdiff1d(a,b) #교차하지 않는걸 찾아주는 함수

array([10, 20, 40])

In [101]:
# random
x= np.random.randint(100)
x

47

In [103]:
x= np.random.randint(100)
x

39

In [105]:
x= np.random.rand(5)
x

array([0.77788808, 0.58663564, 0.10560992, 0.26456563, 0.0882563 ])